on:
  workflow_dispatch: # manually
  schedule:
    - cron: '0 0 * * 0' # at 00:00 every Sunday

jobs:
  check-for-new-gods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'
      - name: Run God Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          go run main.go
          if git diff --quiet --exit-code; then
            echo "::set-env name=has_changes::false"
          else
            echo "::set-env name=has_changes::true"
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ env.has_changes == 'true' }}
        with:
          commit-message: updated with new god
          title: Updated with new God ':eyes:' @bshore
          body: Updated with new God ':eyes:' @bshore
          branch: update-gods
